# Generated by Django 4.0.4 on 2022-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='readcnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
