# Generated by Django 3.2.3 on 2022-06-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Explanation',
            field=models.TextField(max_length=300, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Image_2',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='이미지2'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Place',
            field=models.CharField(max_length=32, unique=True, verbose_name='장소'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Theme',
            field=models.CharField(max_length=32, verbose_name='테마'),
        ),
    ]
