# Generated by Django 4.0.3 on 2022-06-13 07:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristspots', '0003_alter_favoritespot_mytouristspot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('theme', models.TextField(blank=True)),
                ('score', models.TextField(blank=True)),
                ('group', models.TextField(blank=True)),
                ('age', models.TextField(blank=True)),
            ],
        ),
    ]
